name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo’yu çek
      - uses: actions/checkout@v4

      # 2️⃣ dist klasörünü oluştur
      - name: Create dist folder
        run: mkdir -p dist

      # 3️⃣ Snake SVG ve GIF üret
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: berranuralinca
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg

      # 4️⃣ Durumu kontrol et
      - run: git status

      # 5️⃣ SVG’ye dinamik tema CSS ekle (dark/light)
      - name: Add dynamic background to SVG
        run: |
          echo '<style>@media (prefers-color-scheme: dark) { svg { background-color: #000; } } @media (prefers-color-scheme: light) { svg { background-color: #fff; } }</style>' | cat - dist/github-contribution-grid-snake.svg > dist/temp.svg
          mv dist/temp.svg dist/github-contribution-grid-snake.svg

      # 6️⃣ GIF’i kontrastlı yapmak (siyah arka plan)
      - name: Make GIF background black
        run: |
          magick convert dist/github-contribution-grid-snake.gif -background black -alpha remove dist/github-contribution-grid-snake.gif || true

      # 7️⃣ output branch’ine push
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
