name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo’yu çek
      - uses: actions/checkout@v4

      # dist klasörünü oluştur
      - name: Create dist folder
        run: mkdir -p dist

      # Snake SVG ve GIF üret
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: berranuralinca
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg

      # Durumu kontrol et
      - run: git statu
